// <auto-generated />
using System;
using BT_C_.data_access;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BT_C_.data_access.migrations
{
    [DbContext(typeof(CompanyDbContext))]
    partial class CompanyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BT_C_.Models.CongTy", b =>
                {
                    b.Property<int>("CongTyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CongTyId"));

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CongTyId");

                    b.ToTable("CongTys");
                });

            modelBuilder.Entity("BT_C_.Models.NhanVien", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienId"));

                    b.Property<int?>("CongTyId")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("gioitinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NhanVienId");

                    b.HasIndex("CongTyId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("BT_C_.Models.PhongBan", b =>
                {
                    b.Property<int>("PhongBanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongBanId"));

                    b.Property<int>("CongTyId")
                        .HasColumnType("int");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PhongBanId");

                    b.HasIndex("CongTyId");

                    b.ToTable("PhongBans");
                });

            modelBuilder.Entity("BT_C_.Models.NhanVien", b =>
                {
                    b.HasOne("BT_C_.Models.CongTy", "CongTyMaCongTyNavigation")
                        .WithMany()
                        .HasForeignKey("CongTyId");

                    b.HasOne("BT_C_.Models.PhongBan", "PhongBanMaPhongBanNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("PhongBanId");

                    b.Navigation("CongTyMaCongTyNavigation");

                    b.Navigation("PhongBanMaPhongBanNavigation");
                });

            modelBuilder.Entity("BT_C_.Models.PhongBan", b =>
                {
                    b.HasOne("BT_C_.Models.CongTy", "CongTy")
                        .WithMany("PhongBans")
                        .HasForeignKey("CongTyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongTy");
                });

            modelBuilder.Entity("BT_C_.Models.CongTy", b =>
                {
                    b.Navigation("PhongBans");
                });

            modelBuilder.Entity("BT_C_.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
